### PR TITLE
Fix erroneous function call

### PR DESCRIPTION
**Pull request by alloyit**
## PR Checklist

- [x] The PR title follows our guidelines: https://github.com/NativeScript/NativeScript/blob/master/CONTRIBUTING.md#commit-messages.
- [ ] There is an issue for the bug/feature this PR is for. To avoid wasting your time, it's best to open a suggestion issue first and wait for approval before working on it.
- [x] All existing tests are passing
- [ ] Tests for the changes are included

## What is the current behavior?
On iOS this library returned always a truthy values for Jailbreak check, because it was returning the function itself.

## What is the new behavior?
Now it will returns the function returned value.

## BREAKING CHANGES:
None.

### CODE REVIEW

**Comment by shivang-sai** [comment]
Thanks for pointing out.

**Comment by alloyit** [comment]
Hi, the npm/tns repositories have still the old bugged version. Could you please update them with the correct one?

**Comment by shivang-sai** [comment]
I've published a new build. You can bump up the version to 1.0.1 to checkout the new release.

**Comment by alloyit** [comment]
Great! Thanks

**Pull request merged**
